name: FTP Deploy to BigRock
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via FTP
        env:
          HOST: ${{ secrets.FTP_HOST }}
          USERNAME: ${{ secrets.FTP_USERNAME }}
          PASSWORD: ${{ secrets.FTP_PASSWORD }}
          PORT: ${{ secrets.FTP_PORT }}
        run: |
          lftp -c "
          set ftp:ssl-allow no
          open -u $USERNAME,$PASSWORD $HOST
          mirror -R --only-newer --verbose ./ ./
          bye
          "
